kind: pipeline
type: docker
name: immich-photos-deploy

steps:
  - name: create-network
    image: docker:24-cli
    commands:
      - docker network create immich || true
    when:
      branch:
        - main
      event:
        - push

  - name: deploy
    image: docker:24-cli
    commands:
      - apk add --no-cache docker-compose
      - mkdir -p "$UPLOAD_LOCATION" "$DB_DATA_LOCATION"
      - docker-compose down || true
      - docker-compose pull
      - docker-compose up -d
    environment:
      # Environment variables from Drone secrets
      UPLOAD_LOCATION:
        from_secret: UPLOAD_LOCATION
      DB_DATA_LOCATION:
        from_secret: DB_DATA_LOCATION
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_USERNAME:
        from_secret: DB_USERNAME
      DB_DATABASE_NAME:
        from_secret: DB_DATABASE_NAME
      TZ:
        from_secret: TZ
      MACHINE_LEARNING_WORKERS:
        from_secret: MACHINE_LEARNING_WORKERS
      MACHINE_LEARNING_WORKER_TIMEOUT:
        from_secret: MACHINE_LEARNING_WORKER_TIMEOUT
      IMMICH_VERSION:
        from_secret: IMMICH_VERSION
    depends_on:
      - create-network
    when:
      branch:
        - main
      event:
        - push

  - name: health-check
    image: docker:24-cli
    commands:
      - sleep 30
      - docker-compose ps
      - docker-compose logs --tail=50 immich-server
    depends_on:
      - deploy
    when:
      branch:
        - main
      event:
        - push



