services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - traefik
      - immich
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # HTTP router for redirect
      - traefik.http.routers.immich-web.rule=Host(`photos.waugze.com`)
      - traefik.http.routers.immich-web.entrypoints=web
      - traefik.http.routers.immich-web.middlewares=immich-redirect
      # HTTPS router
      - traefik.http.routers.immich.rule=Host(`photos.waugze.com`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=letsencrypt
      # Redirect middleware
      - traefik.http.middlewares.immich-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.immich-redirect.redirectscheme.permanent=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      # Fix for large uploads (important!)
      # - traefik.http.routers.immich.middlewares=immich-timeout
      # - traefik.http.middlewares.immich-timeout.timeout.response=0s

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

volumes:
  model-cache:

networks:
  traefik:
    external: true
  immich:
    driver: bridge
